[package]
name = "egwidget"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
notify = "8.0.0"
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
walkdir = "2.5.0"
