# MyCard.toml

[template]
name       = "MyCard"
parameters = ["title", "body"]

widget_type = "Frame"
id          = "MyCard"

[properties.inner_margin]
left   = 8.0
right  = 8.0
top    = 8.0
bottom = 8.0

# Here we use a shorthand for children: a list of
# TOML tables with either `text` or no extra props.
children = [
  { widget = "Label", text = "${title}" },
  { widget = "Separator"          },
  { widget = "Label", text = "${body}"  },
]
